version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: '08:00'
  open-pull-requests-limit: 99
- package-ecosystem: terraform
  directory: "terraform"
  schedule:
    interval: daily
    time: '08:00'
  open-pull-requests-limit: 99
- package-ecosystem: github-actions
  directory: ".github"
  schedule:
    interval: daily
    time: '08:00'
  open-pull-requests-limit: 99